/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.edu.agh.kis.core.panels;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import pl.edu.agh.kis.core.utilities.BpmnFilter;

/**
 *
 * @author Jakub Piotrowski
 */
public class GeneratorPanel extends javax.swing.JPanel {

    private File bpmnFile;
    
    /**
     * Creates new form GeneratorPanel
     */
    public GeneratorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pathTextField = new javax.swing.JTextField();
        chooseBpmnButton = new javax.swing.JButton();
        chooseLogicFormulasButton = new javax.swing.JButton();
        generateButton = new javax.swing.JButton();
        graphPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logicFormulasTextField = new javax.swing.JTextPane();
        enlargeLogicFormulasButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        patternsTextField = new javax.swing.JTextPane();
        enlargePatternsButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        generatedLogicTextField = new javax.swing.JTextPane();
        enlargeGeneratedLogicButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        pathTextField.setText(org.openide.util.NbBundle.getMessage(GeneratorPanel.class, "GeneratorPanel.pathTextField.text")); // NOI18N
        pathTextField.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 5);
        add(pathTextField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(chooseBpmnButton, org.openide.util.NbBundle.getMessage(GeneratorPanel.class, "GeneratorPanel.chooseBpmnButton.text")); // NOI18N
        chooseBpmnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBpmnButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        add(chooseBpmnButton, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(chooseLogicFormulasButton, org.openide.util.NbBundle.getMessage(GeneratorPanel.class, "GeneratorPanel.chooseLogicFormulasButton.text")); // NOI18N
        chooseLogicFormulasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLogicFormulasButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        add(chooseLogicFormulasButton, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(generateButton, org.openide.util.NbBundle.getMessage(GeneratorPanel.class, "GeneratorPanel.generateButton.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 10);
        add(generateButton, gridBagConstraints);

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 8.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(graphPanel, gridBagConstraints);

        logicFormulasTextField.setEnabled(false);
        jScrollPane1.setViewportView(logicFormulasTextField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 5);
        add(jScrollPane1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(enlargeLogicFormulasButton, org.openide.util.NbBundle.getMessage(GeneratorPanel.class, "GeneratorPanel.enlargeLogicFormulasButton.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 10);
        add(enlargeLogicFormulasButton, gridBagConstraints);

        patternsTextField.setEnabled(false);
        jScrollPane2.setViewportView(patternsTextField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(jScrollPane2, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(enlargePatternsButton, org.openide.util.NbBundle.getMessage(GeneratorPanel.class, "GeneratorPanel.enlargePatternsButton.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        add(enlargePatternsButton, gridBagConstraints);

        generatedLogicTextField.setEnabled(false);
        jScrollPane3.setViewportView(generatedLogicTextField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        add(jScrollPane3, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(enlargeGeneratedLogicButton, org.openide.util.NbBundle.getMessage(GeneratorPanel.class, "GeneratorPanel.enlargeGeneratedLogicButton.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        add(enlargeGeneratedLogicButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void chooseBpmnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBpmnButtonActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.addChoosableFileFilter(new BpmnFilter());
        fc.setAcceptAllFileFilterUsed(false);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            bpmnFile = fc.getSelectedFile();
            pathTextField.setText(bpmnFile.getAbsolutePath());
        }
    }//GEN-LAST:event_chooseBpmnButtonActionPerformed

    private void chooseLogicFormulasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLogicFormulasButtonActionPerformed
        JDialog dialog = new JDialog();
        dialog.setModal(true);
        dialog.setTitle("Formuły logiki temporalnej");
        dialog.setSize(600, 400);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - dialog.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - dialog.getHeight()) / 2);
        dialog.setLocation(x, y);
        
        dialog.getContentPane().add(new LogicFormulasPanel());
        dialog.setVisible(true);
    }//GEN-LAST:event_chooseLogicFormulasButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseBpmnButton;
    private javax.swing.JButton chooseLogicFormulasButton;
    private javax.swing.JButton enlargeGeneratedLogicButton;
    private javax.swing.JButton enlargeLogicFormulasButton;
    private javax.swing.JButton enlargePatternsButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JTextPane generatedLogicTextField;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane logicFormulasTextField;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JTextPane patternsTextField;
    // End of variables declaration//GEN-END:variables
}
